# Generated by Django 3.2.13 on 2022-07-14 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Best Seller', 'Best Seller'), ('Favorites', 'Favorites'), ('Special', 'Special'), ('Out Of Stock', 'Out Of Stock')], default='Favorite', max_length=50)),
                ('food_image', models.ImageField(blank=True, null=True, upload_to='food_img/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('food', models.ManyToManyField(related_name='foods', to='ordering.Food')),
            ],
        ),
    ]
