# Generated by Django 3.2.13 on 2022-08-22 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('avatar', models.ImageField(upload_to='testimonial/avatar/')),
                ('post_origin', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='food',
            name='status',
            field=models.CharField(choices=[('Best Seller', 'Best Seller'), ('Favorites', 'Favorites'), ('Special', 'Special'), ('Out Of Stock', 'Out Of Stock')], default='Favorites', max_length=50),
        ),
    ]
