# Generated by Django 3.2.13 on 2022-08-22 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0002_auto_20220822_0317'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Testimonials',
            new_name='Testimonial',
        ),
    ]
