# Generated by Django 3.2.13 on 2022-08-22 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0003_rename_testimonials_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='testimonial/avatar/'),
        ),
    ]
