# Generated by Django 3.2.13 on 2022-09-10 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0007_auto_20220910_0311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='checkout',
        ),
        migrations.DeleteModel(
            name='Checkout',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
