# Generated by Django 3.2.13 on 2022-09-11 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0008_auto_20220910_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='middle_initial',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
