# Generated by Django 3.2.13 on 2022-09-12 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0011_auto_20220912_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barangay',
            name='shipping_fee',
            field=models.IntegerField(),
        ),
    ]
