# Generated by Django 3.2.13 on 2022-09-14 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0012_alter_barangay_shipping_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='barangay',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='barangay', to='ordering.barangay'),
            preserve_default=False,
        ),
    ]
