# Generated by Django 3.2.13 on 2022-09-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0013_profile_barangay'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Cancel', 'Cancel'), ('Ongoing', 'Ongoing'), ('Recieved', 'Recieved')], default='Ongoing', max_length=20),
        ),
    ]
