# Generated by Django 3.2.13 on 2022-11-01 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ordering', '0014_order_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CateringSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['created_at']},
        ),
        migrations.CreateModel(
            name='CateringReserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_package', models.CharField(choices=[('Package A', 'Package A'), ('Package B', 'Package B'), ('Package C', 'Package C'), ('Package D', 'Package D'), ('Package E', 'Package E'), ('Package F', 'Package F'), ('Customize', 'Customize')], default='Package A', max_length=10)),
                ('reserve_status', models.CharField(choices=[('Approve', 'Approve'), ('Ongoing/Pending', 'Ongoing/Pending'), ('Disapprove', 'Disapprove')], default='Ongoing/Pending', max_length=20)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catering_date', to='ordering.cateringschedule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catering_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
