# Generated by Django 3.2.13 on 2022-11-01 12:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0015_auto_20221101_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='cateringreserve',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cateringreserve',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cateringreserve',
            name='reserve_status',
            field=models.CharField(choices=[('Approve', 'Approve'), ('Ongoing/Pending', 'Ongoing/Pending'), ('Disapprove', 'Disapprove'), ('Cancel', 'Cancel')], default='Ongoing/Pending', max_length=20),
        ),
    ]
