# Generated by Django 3.2.13 on 2022-11-07 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0016_auto_20221101_2017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cateringreserve',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='cateringreserve',
            name='date',
            field=models.DateField(),
        ),
    ]
