# Generated by Django 3.2.13 on 2022-11-07 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0017_auto_20221107_1250'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CateringSchedule',
        ),
    ]
