# Generated by Django 3.2.13 on 2022-11-07 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0018_delete_cateringschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='CateringSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='cateringreserve',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catering_date', to='ordering.cateringschedule'),
        ),
    ]
