# Generated by Django 3.2.13 on 2022-11-07 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0019_auto_20221107_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cateringreserve',
            name='date',
            field=models.DateField(unique=True),
        ),
        migrations.DeleteModel(
            name='CateringSchedule',
        ),
    ]
