# Generated by Django 3.2.13 on 2022-11-07 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0020_auto_20221107_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cateringreserve',
            name='date',
            field=models.DateField(unique_for_date=True),
        ),
    ]
